version: 0.2
env:
  shell: bash
phases:
  pre_build:
    commands:
      - mkdir /downloads/sonarqube -p
      - cd /downloads/sonarqube
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.2.0.1873-linux.zip
      - unzip sonar-scanner-cli-4.2.0.1873-linux.zip
      - mv sonar-scanner-4.2.0.1873-linux /opt/sonar-scanner
      - echo -e "sonar.host.url=https://sonarcloud.io \n  sonar.sourceEncoding=UTF-8 " >> /opt/sonar-scanner/conf/sonar-scanner.properties
      - echo -e "#/bin/bash \n export PATH='$PATH:/opt/sonar-scanner/bin'" >> /etc/profile.d/sonar-scanner.sh
      - source /etc/profile.d/sonar-scanner.sh
      - sonar-scanner -v
  build:
    commands:
      - cd ../..
      - cd /codebuild/output/
      - sonar-scanner -Dsonar.projectKey=aws_code_PHPDevSecOps -Dsonar.organization=gastonbarbaccia -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=8abff51dcbcac992a96e53d3e35f1b424e85aeec -Dsonar.scm.disabled=True -Dsonar.java.binaries=/tmp/empty


